### ISSUE TITLE
Filters when searching for a specific batch id is not working

### ISSUE THREAD

**Issue by superfoght** [sebsoftnl/moodle-block_coupon#16]
If I try to search for a specific batch id: 
![image](https://github.com/sebsoftnl/moodle-block_coupon/assets/2778015/9573b520-c0db-40cf-aa26-940bdf1a9573)

It doesn't find anything. Instead it sets two empty filters:

![image](https://github.com/sebsoftnl/moodle-block_coupon/assets/2778015/16019a7d-fd32-4430-8a68-db985fff20d0)

**Comment by lopluca** [comment]
Hi. I encountered the same problem. Have you solved? then why are there two filters on batch id?

**Comment by frederikmillingpytlick** [comment]
See:
https://github.com/sebsoftnl/moodle-block_coupon/pull/17

**Comment by rogiervandongen** [comment]
@superfoght @lopluca 
This is all fixed in the next version (soon to be released).
It took a while but we had extremely little time due to paid projects which always come first.

Please do mind that the "simple" dropdown has been replaced by an autocomplete.
This doesn't always make it easier especially with the batch IDs, but the change was made for good reason:

we increasingly got notified by some of our customers that make extremely heavy use of this plugin and walked into the problem that the browser would crash.
The reason? well over 50,000 batchid's. The browser did _not_ like having to render all of those, frequently leading to seemingly hanging pages or the browser going out of memory.
With that in mind the decisio0n was made to convert the simple dropdown for an autocomplete one.
