### ISSUE TITLE
upgrade to Moodle 4.3 with PHP 8.1 - Filter data not active

### ISSUE THREAD

**Issue by vman002** [sebsoftnl/moodle-block_coupon#20]
With Coupon build: 2022090100 - v4.2.1
Upon attempted use of any "Filters" the following error generated and Filter not activated.
Exception - array_key_exists(): Argument #2 ($array) must be of type array, stdClass given

In addition, past "Generated Codes" do not indicate "Claimed by". All codes indicate: "Course not started yet" when many are in various states of completion.

Could be database connection issue. vmartin@oetc.ca

Moodle version 4.3+ (updated recently from v3.6)
PHP version 8.1.16
SQL version: 10.6.16-MariaDB

**Comment by rogiervandongen** [comment]
@vman002 
Thanks for noticing. I was working this list down->up and already walked into this specific issue.... for literally every single custom filter.
With PHP becoming more and more strict (thankfully!!), code that worked before (even when utterly wrong) will now crash fatally.
This is such an issue: the data that was "investigated" is _not an _array. However, due to PHP's historical inner workings, array and object are more or less interchangeable and core PHP "didn't really care for either". This also meant a lot of functions would work on both even when it's wrong from a strict POV.
Such is the case with "array_key_exists" vs "property_exists". Modern PHP no longer allows this dualist behaviour.
Code is fixed internally, will come along on next release.
