### ISSUE TITLE
Bugs in Login and Submitting Coupon

### ISSUE THREAD

**Issue by peter-lernyx** [sebsoftnl/moodle-block_coupon#9]
I am experiencing diffuculties in using the coupon plugin.
- Moodle 3.11
- Snap Template 3.11.5
- php 7.4.29
 I am attaching a short video showing the problem. The coupon used is meant to automatically enrol the new user in a cohort.

The error message leads me to believe that there is possibly a type mismatch in the database (numeric vs. string?). I've had something similar in an entirely different context, but not at all sure. Here ist the line 198 from auth.php that the error message is referring to:

**`198 list($availableenrolids, $errors) = $this->enrol_user($user->signup_token, $notify);`**

Here is the first error message that you see directly after attempted login:

![grafik](https://user-images.githubusercontent.com/75390480/166442099-3e300539-6acc-4a64-9edd-db1ee8bf8770.png)

and here is the video about the entire process:

https://user-images.githubusercontent.com/75390480/166442428-e9d84b55-35f6-4967-850b-69c80b000d8e.mp4

**Comment by peter-lernyx** [comment]
Update: I have disabled Enrolment-Key-login and the process seems to work fine now. The two seem to clash.

**Comment by rogiervandongen** [comment]
Hi Peter,
Thanks for sharing this!
It's been a while since I could work on this project (paid projects will always overrule community work).
The two plugin obviously indeed seem to collide.
I will try to recreate a scenario and hopefully tackle it.

The cohort methods are not widely in use (it was designed for a specific client at some point) so it's always nice to see a case where the cohort coupon method is actually in use.

It seems that either there were significant changes to the core, or we've never encountered this case (which is realistic enough considering the fact most installations don't or didn't have that much enrolment methods activated or in use).
